apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: electronix

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      nodeSelector:
         workload: application

      containers:
      - name: frontend

        image: vishwajeetkumar938/electronix-frontend:1.0

        ports:
        - containerPort: 80